# 'version' is obsolete and has been removed
services:
  webserver:
    # This tells Docker Compose to build the image from the Dockerfile
    # in the current directory '.'
    build: .
    image: asm-webserver # It's good practice to still name the image
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot